export const Questions = [
  {
    questionText: "Jag föredrar att lägga tid på att tänka på...",
    answers: [
      {
        answerText: "Teori",
        questioner: 0.4,
        solver: 0.25,
        connector: 0.2,
        advocator: 0.66,
        trackingId: "theory",
      },
      {
        answerText: "Verkliga livet",
        questioner: 0.6,
        solver: 0.75,
        connector: 0.8,
        advocator: 0.34,
        trackingId: "life",
      },
    ],
  },
  {
    questionText: "Jag skulle hellre spendera min tid...",
    answers: [
      {
        answerText: "Att slutföra ett pussel",
        questioner: 0.2,
        solver: 0.6,
        connector: 0.3,
        advocator: 0.1,
        trackingId: "puzzle",
      },
      {
        answerText: "Svara på en fråga genom att använda internet",
        questioner: 0.6,
        solver: 0.3,
        connector: 0.3,
        advocator: 0.8,
        trackingId: "internet",
      },
      {
        answerText: "Att skriva en berättelse",
        questioner: 0.2,
        solver: 0.1,
        connector: 0.4,
        advocator: 0.1,
        trackingId: "writing",
      },
    ],
  },
  {
    questionText: "När jag städar...",
    answers: [
      {
        answerText: "Gör jag en uppgift i taget tills jag är klar",
        questioner: 0.6,
        solver: 0.6,
        connector: 0.7,
        advocator: 0.4,
        trackingId: "one-at-a-time",
      },
      {
        answerText: "Tar paus mellan varje uppgift",
        questioner: 0.4,
        solver: 0.4,
        connector: 0.3,
        advocator: 0.6,
        trackingId: "take-breaks",
      },
    ],
  },
  {
    questionText: "Jag skulle hellre se...",
    answers: [
      {
        answerText: "En spännande actionfilm",
        questioner: 0.2,
        solver: 0.2,
        connector: 0.6,
        advocator: 0.3,
        trackingId: "action",
      },
      {
        answerText: "Ett karaktärsdrivet drama",
        questioner: 0.6,
        solver: 0.3,
        connector: 0.2,
        advocator: 0.4,
        trackingId: "drama",
      },
      {
        answerText: "En insiktsfull dokumentär om hur saker är uppbyggda",
        questioner: 0.2,
        solver: 0.5,
        connector: 0.2,
        advocator: 0.3,
        trackingId: "documentary",
      },
    ],
  },
  {
    questionText: "När jag ser en tavla så...",
    answers: [
      {
        answerText: "Beundrar jag den för hur fin den är",
        questioner: 0.4,
        solver: 0.3,
        connector: 0.1,
        advocator: 0.7,
        trackingId: "beauty",
      },
      {
        answerText:
          "Funderar jag på vad som gör denna målning populär och viktig",
        questioner: 0.3,
        solver: 0.5,
        connector: 0.8,
        advocator: 0.2,
        trackingId: "important",
      },
      {
        answerText: "Undrar vilka tekniker en målare använde för att måla den",
        questioner: 0.3,
        solver: 0.2,
        connector: 0.1,
        advocator: 0.1,
        trackingId: "techniques",
      },
    ],
  },
  {
    questionText: "När jag lagar ett recept...",
    answers: [
      {
        answerText: "Följer jag instruktionerna noggrant",
        questioner: 0.4,
        solver: 0.6,
        connector: 0.5,
        advocator: 0.1,
        trackingId: "precise",
      },
      {
        answerText: "Tittar på bilden och improviserar",
        questioner: 0.2,
        solver: 0.2,
        connector: 0,
        advocator: 0.1,
        trackingId: "wing-it",
      },
      {
        answerText: "Provsmakar och justerar om det behövs",
        questioner: 0.4,
        solver: 0.2,
        connector: 0.5,
        advocator: 0.8,
        trackingId: "adjust",
      },
    ],
  },
  {
    questionText: "Vad stämmer mest in på mig:",
    answers: [
      {
        answerText: "Letar upp saker eftersom jag behöver svar på dem",
        questioner: 0.6,
        solver: 0.6,
        connector: 0.4,
        advocator: 0.1,
        trackingId: "look-it-up",
      },
      {
        answerText: "Att lära sig allt om ett ämne",
        questioner: 0.1,
        solver: 0.1,
        connector: 0,
        advocator: 0.4,
        trackingId: "learn-everything",
      },
      {
        answerText: "Att kunna en sammanfattning av tio ämnen på hög nivå",
        questioner: 0.3,
        solver: 0.3,
        connector: 0.6,
        advocator: 0.5,
        trackingId: "summary",
      },
    ],
  },
  {
    questionText: "Jag tenderar att se livet genom linsen av...",
    answers: [
      {
        answerText: "Bilder",
        questioner: 0,
        solver: 0,
        connector: 0.1,
        advocator: 0.3,
        trackingId: "pictures",
      },
      {
        answerText: "System",
        questioner: 0.3,
        solver: 0.7,
        connector: 0.6,
        advocator: 0.3,
        trackingId: "systems",
      },
      {
        answerText: "Historier",
        questioner: 0.7,
        solver: 0.3,
        connector: 0.3,
        advocator: 0.4,
        trackingId: "stories",
      },
    ],
  },
];
